---
hostname: sw1
ansible_host: 172.16.100.121
id: 121

mgmt_intf: GigabitEthernet0/0

interfaces:
  - type: GigabitEthernet
    number: 0/1
    description: RTR1-GE2
  - type: GigabitEthernet
    number: 0/2
    description: RTR1-GE3
  - type: GigabitEthernet
    number: 3/0
    description: PC1-ENS3